# Generated by Django 2.2.6 on 2019-11-05 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.localdate)),
                ('expire_date', models.DateTimeField()),
                ('valid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lista de Compra',
                'verbose_name_plural': 'Lista de Compras',
                'ordering': ['-created_date'],
            },
        ),
    ]
