# Generated by Django 2.2.6 on 2019-11-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'ordering': ['expire_date'], 'verbose_name': 'Lista de Compra', 'verbose_name_plural': 'Lista de Compras'},
        ),
        migrations.AddField(
            model_name='lista',
            name='dias',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
