# Generated by Django 2.2.6 on 2019-10-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='desc',
            field=models.CharField(default='Descrição', max_length=50),
        ),
    ]
