# Generated by Django 2.2.6 on 2019-10-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_lista_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='desc',
        ),
    ]
