# Generated by Django 2.2.6 on 2019-11-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_auto_20191105_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='atencao',
            field=models.BooleanField(default=False),
        ),
    ]
